### ISSUE TITLE
Getting session expired error

### ISSUE THREAD

**Issue by eswaran88** [rainmattertech/javakiteconnect#2]

**Comment by kssujithcj** [comment]
Hi,
Request token validity is for 5 min and it can only be used only once. So once you get access token store it and use the same, don't call requestAccessToken() every time you run the app.

**Comment by eswaran88** [comment]
I didn't get any token from response, Kindly check from your end.

**Comment by kssujithcj** [comment]
@eswaran88,
It is mandatory by the exchange that a user has to log in manually at least once a day.
You need to login on browser, after successful login, you will get request token
